# Generated by Django 2.0.7 on 2018-07-31 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_personalnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalnote',
            name='note_ptr',
        ),
        migrations.RemoveField(
            model_name='personalnote',
            name='user',
        ),
        migrations.DeleteModel(
            name='PersonalNote',
        ),
    ]
